kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-evs-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-evs-plugin
  template:
    metadata:
      labels:
        app: csi-evs-plugin
    spec:
      tolerations:
        - operator: Exists
      serviceAccount: csi-evs-node-sa
      containers:
        - name: evs-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/evs.csi.huaweicloud.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.5.0
          args:
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: evs-csi-plugin
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
              drop:
                - all
            privileged: true
            readOnlyRootFilesystem: true
          image: swr.cn-north-4.myhuaweicloud.com/k8s-csi/evs-csi-plugin:v0.1.11
          args:
            - /bin/evs-csi-plugin
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-config=$(CLOUD_CONFIG)"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/evs/cloud-config
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          # The probe
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: pass-pods-mount-dir
              mountPath: /mnt/paas/kubernetes/kubelet
              mountPropagation: Bidirectional
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: host-sys
              mountPath: /sys
              readOnly: true
            - name: host-run-udev
              mountPath: /run/udev
              readOnly: true
            - name: evs-config
              mountPath: /etc/evs/
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/evs.csi.huaweicloud.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pass-pods-mount-dir
          hostPath:
            path: /mnt/paas/kubernetes/kubelet
            type: DirectoryOrCreate
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - hostPath:
            path: /sys
            type: Directory
          name: host-sys
        - hostPath:
            path: /run/udev
            type: Directory
          name: host-run-udev
        - name: evs-config
          secret:
            secretName: cloud-config
