apiVersion: v1
kind: Pod
metadata:
  name: nginx-obs
spec:
  containers:
    - image: nginx
      name: nginx-obs
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /mnt/obs/outfile; sleep 5; done"]
      volumeMounts:
        - mountPath: /mnt/obs
          name: obs-data
  volumes:
    - name: obs-data
      persistentVolumeClaim:
        claimName: pvc-obs
